name: Android CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.6
        bundler-cache: true
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Install Bundler
      run: gem install bundler --no-document -v $(grep "BUNDLED WITH" -1 Gemfile.lock | tail -n 1)
    - name: Bundle install
      run: bundle install --path=vendor/bundle --jobs 4 --retry 3
    - name: fastlane
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec fastlane review

