# This is a basic workflow to help you get started with Actions

name: Qodana - Code Inspection

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  qodana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: composer install
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v2.0-eap
        with:
            project-dir: ${{ github.workspace }}
            results-dir: ${{ github.workspace }}/docs
            cache-dir: /home/runner/work/_temp/_github_home/qodana-cache
      - name: Count changes
        id: changes
        run: |
          git add -N docs
          echo "::set-output name=count::$(git diff --name-only docs | wc -l)"
      - name: Deploy to GitHub Pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "[skip ci]"
          git push
        if: steps.changes.outputs.count > 0
      - uses: actions/upload-artifact@v2
        with:
          name: result
          path: qodana
      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: docs
